### ISSUE TITLE
CLI produces self signed cert error on NG

### ISSUE THREAD

**Issue by Conjur-oss** [cyberark/conjur-api-python3#333]
##Bug description
Description:

One _*first*_ init attempt to a new cluster on ng machines, we get the following error. If you run init again, it will pass. The same process was run in a non-ng machine and on first init, it worked.

 

 
{code:java}
File "/Users/Sigal.Sax/brew/lib/python3.9/site-packages/conjur/wrapper/http_wrapper.py", line 110, in invoke_request
 raise ssl_error
 File "/Users/Sigal.Sax/brew/lib/python3.9/site-packages/conjur/wrapper/http_wrapper.py", line 100, in invoke_request
 return request_method(url, *args,
 File "/Users/Sigal.Sax/brew/lib/python3.9/site-packages/requests/api.py", line 76, in get
 return request('get', url, params=params, **kwargs)
 File "/Users/Sigal.Sax/brew/lib/python3.9/site-packages/requests/api.py", line 61, in request
 return session.request(method=method, url=url, **kwargs)
 File "/Users/Sigal.Sax/brew/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
 resp = self.send(prep, **send_kwargs)
 File "/Users/Sigal.Sax/brew/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
 r = adapter.send(request, **kwargs)
 File "/Users/Sigal.Sax/brew/lib/python3.9/site-packages/requests/adapters.py", line 514, in send
 raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='ec2-3-127-155-226.eu-central-1.compute.amazonaws.com', port=443): Max retries exceeded with url: /info (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
Failed to execute command. Reason: HTTPSConnectionPool(host='ec2-3-127-155-226.eu-central-1.compute.amazonaws.com', port=443): Max retries exceeded with url: /info (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
 
{code}
Steps to reproduce:
 # Deploy cluster
 # On non-ng machine, Install conjur CLI
 # conjur init -u https://<your dns>
 # Pass
 # On ng machine, install conjur CLI
 # conjur init -u https://<your dns>
 # Fail on first try
 # Try init again, pass

 

Current Results:

We fail to init using the CLI on first attempt on ng-machines

Expected Results:
 # Add another retry
 # Present readible error

Error Messages:

Logs:
{code:java}
During handling of the above exception, another exception occurred:Traceback (most recent call last):
  File "/Users/Sigal.Sax/brew/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/Sigal.Sax/brew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/Users/Sigal.Sax/brew/lib/python3.9/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ec2-3-127-155-226.eu-central-1.compute.amazonaws.com', port=443): Max retries exceeded with url: /info (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))During handling of the above exception, another exception occurred:Traceback (most recent call last):
  File "/Users/Sigal.Sax/brew/lib/python3.9/site-packages/conjur/cli.py", line 546, in run
    Cli.run_action(resource, args)
  File "/Users/Sigal.Sax/brew/lib/python3.9/site-packages/conjur/cli.py", line 716, in run_action
    Cli.handle_init_logic(args.url, args.name, args.certificate, args.force, args.ssl_verify)
  File "/Users/Sigal.Sax/brew/lib/python3.9/site-packages/conjur/cli.py", line 600, in handle_init_logic
    input_controller.load()
  File "/Users/Sigal.Sax/brew/lib/python3.9/site-packages/conjur/controller/init_controller.py", line 60, in load
    self.get_account_info(self.conjurrc_data)
  File "/Users/Sigal.Sax/brew/lib/python3.9/site-packages/conjur/controller/init_controller.py", line 133, in get_account_info
    self.init_logic.fetch_account_from_server(self.conjurrc_data)
  File "/Users/Sigal.Sax/brew/lib/python3.9/site-packages/conjur/logic/init_logic.py", line 68, in fetch_account_from_server
    response = invoke_endpoint(HttpVerb.GET,
  File "/Users/Sigal.Sax/brew/lib/python3.9/site-packages/conjur/wrapper/http_wrapper.py", line 69, in invoke_endpoint
    response = invoke_request(http_verb,
  File "/Users/Sigal.Sax/brew/lib/python3.9/site-packages/conjur/wrapper/http_wrapper.py", line 110, in invoke_request
    raise ssl_error
  File "/Users/Sigal.Sax/brew/lib/python3.9/site-packages/conjur/wrapper/http_wrapper.py", line 100, in invoke_request
    return request_method(url, *args,
  File "/Users/Sigal.Sax/brew/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/Sigal.Sax/brew/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/Sigal.Sax/brew/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Sigal.Sax/brew/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Sigal.Sax/brew/lib/python3.9/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='ec2-3-127-155-226.eu-central-1.compute.amazonaws.com', port=443): Max retries exceeded with url: /info (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))Failed to execute command. Reason: HTTPSConnectionPool(host='ec2-3-127-155-226.eu-central-1.compute.amazonaws.com', port=443): Max retries exceeded with url: /info (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
{code}
Other Symptoms:

Tenant ID / Pod Number:

##Found in version
12.3

##Workaround Complexity
There's an easy workaround

##Workaround Description
Rerun init

##Affects Version/s

##Link to JIRA bug
https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-11838

**Comment by Conjur-oss** [comment]
https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-11838

**Comment by Conjur-oss** [comment]
//Author: Matan.Benita@cyberark.com

Another way to reproduce this. is by init to the LB and switch to the Master.
Anytime a switch is happening this is being reproduce.
My guess it something to do with the .conjurrc file

**Comment by Conjur-oss** [comment]
//Author: Sigal.Sax@cyberark.com

[~mbenita]happens with each switch? or just once? happens also in non-NG computers?

**Comment by Conjur-oss** [comment]
//Author: Matan.Benita@cyberark.com

After some investigation we found the followings:
  
 # on the *first attempt* to reach *new conjur server* from *ng-computer* we appears to be failing
 # The certificate we get from the server on the first try is different from the cert getting in the second try
 # The certificate we get in the second run is the one issued by conjur server.
 # The certificate we get in the first run is issued by cyberark. weird :P
 # It is probably served by global protect (Sacha c idea) which tries to act as man in the middle with untrusted ca's
 # on the second attempt GP stop the MITM attemps
 # Need to verify: does this happens with trusted CA's. we think that this will not reproduced in that case
 # It is also possible we are failing because the cyberark intermidiate CA due date is 2033 and we have a restriction validating cert duration to 10 years max.
 # Another thing. our cli doesn't take it rootCA from the machine CA trusted certificate. this is:
 ## security issue
 ## will cause this error always repeat itself with customers self signed CA's


Fo conclusion:
 # Need to verify if it's still working with cyberark root CA trusted by the cli
 # Need to verify if the intermediate  CA life duration is an issue
 # Need to make the CLI work with the machine trusted CAs

**Comment by Conjur-oss** [comment]
//Author: Elad.Kugman@cyberark.com

Duplicate to https://ca-il-jira.il.cyber-ark.com:8443/browse/CONJSE-989
